project_id = "piwahxgtsxpcrgoyuedy"

[functions.rentcast-lookup]
verify_jwt = false

[functions.property-lookup]
verify_jwt = false

[functions.send-letter-followup]
verify_jwt = false

[functions.contact-form]
verify_jwt = false

[functions.hcr-lookup]
verify_jwt = false
